version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform init -upgrade
      - terraform apply -auto-approve -var "app_name=$IMAGE_NAME"